feat: add environment variable validation and fixed, finalize script

diff --git a/ask b/ask
--- a/ask
+++ b/ask
@@ -1,11 +1,23 @@
 #!/bin/bash
 
-[! -t 0] && [-p /dev/stdin] && piped_input=$(cat) || piped_input=""
+if [ -z "$ASK_API_URL" ] || [ -z "$ASK_MODEL" ] || [ -z "$ASK_API_KEY" ]; then 
+
+    echo "ERROR: Required environment variables are missing!" 
+    echo "Please define the following before running the script:" 
+    echo "export ASK_API_URL='...'" 
+    echo "export ASK_MODEL='...'" 
+    echo "export ASK_API_KEY='...'" 
+
+    exit 1
+
+fi 
+
+[ ! -t 0 ] && [ -p /dev/stdin ] && piped_input=$(cat) || piped_input=""
 user_prompt="$piped_input $@"
 
 API_KURALI="You are a CLI tool. Output plain text only. No yapping. Keep the output concise."
 
-payload=$(jq -n \
+payload=$(./jq -n \
     --arg mdl "$ASK_MODEL" \
     --arg sys_msg "$API_KURALI" \
     --arg usr_msg  "$user_prompt" \
@@ -25,4 +37,4 @@ response=$(curl --silent \
     --data "$payload"
 )
 
-echo "$response" | jq -r '.choices[0].message.content'
+echo "$response" | ./jq -r '.choices[0].message.content'
